package com.tiburela.qsercom.testDELETE;

import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.material.textfield.TextInputEditText;
import com.tiburela.qsercom.R;

public class Selector extends AppCompatActivity {


    private TextView mTextView54;
    private TextInputLayout mLasdtwwe;
    private TextInputEditText mEdiLargDeds1;
    private TextInputEditText mEdiLargDeds2;
    private TextInputLayout mTdf;
    private TextInputEditText mEdiLargDeds3;
    private TextInputEditText mEdiLargDeds4;
    private TextInputEditText mEdiLargDeds5;
    private TextInputEditText mEdiLargDeds6;
    private TextInputEditText mEdiLargDeds7;
    private TextInputEditText mEdiLargDeds8;
    private TextInputEditText mEdiLargDeds9;
    private TextInputEditText mEdiLargDeds10;
    private TextInputEditText mEdiLargDeds11;
    private TextInputEditText mEdiLargDeds12;
    private TextInputEditText mEdiLargDeds13;
    private TextInputEditText mEdiLargDeds14;
    private TextInputEditText mEdiLargDeds15;
    private TextInputEditText mEdiLargDeds16;
    private TextInputEditText mEdiLargDeds17;
    private TextInputEditText mEdiLargDeds18;
    private TextInputEditText mEdiLargDeds19;
    private TextInputEditText mEdiLargDeds20;
    private TextInputEditText mEdiLargDeds21;
    private TextInputEditText mEdiLargDeds22;
    private TextInputEditText mEdiLargDeds23;
    private TextInputEditText mEdiLargDeds24;
    private TextInputEditText mEdiLargDeds25;
    private TextInputEditText mEdiLargDeds26;
    private TextInputEditText mEdiLargDeds27;
    private TextInputEditText mEdiLargDeds28;
    private TextInputEditText mEdiLargDeds29;
    private TextInputLayout mLast2;
    private TextInputEditText mEdiLargDeds30;
    private TextInputEditText mEdiTotalFila1;
    private TextInputEditText mEdiPromFila1;
    private TextInputLayout mLast2234;
    private LinearLayout mLy2mm;
    private TextInputEditText mEdif2LrgD1;
    private TextInputEditText mEdif2LrgD2;
    private TextInputEditText mEdif2LrgD3;
    private TextInputEditText mEdif2LrgD4;
    private TextInputEditText mEdif2LrgD5;
    private TextInputEditText mEdif2LrgD6;
    private TextInputEditText mEdif2LrgD7;
    private TextInputEditText mEdif2LrgD8;
    private TextInputEditText mEdif2LrgD9;
    private TextInputEditText mEdif2LrgD10;
    private TextInputEditText mEdif2LrgD11;
    private TextInputEditText mEdif2LrgD12;
    private TextInputEditText mEdif2LrgD13;
    private TextInputEditText mEdif2LrgD14;
    private TextInputEditText mEdif2LrgD15;
    private TextInputEditText mEdif2LrgD16;
    private TextInputEditText mEdif2LrgD17;
    private TextInputEditText mEdif2LrgD18;
    private TextInputEditText mEdif2LrgD19;
    private TextInputEditText mEdif2LrgD20;
    private TextInputEditText mEdif2LrgD21;
    private TextInputEditText mEdif2LrgD22;
    private TextInputEditText mEdif2LrgD23;
    private TextInputEditText mEdif2LrgD24;
    private TextInputEditText mEdif2LrgD25;
    private TextInputEditText mEdif2LrgD26;
    private TextInputEditText mEdif2LrgD27;
    private TextInputEditText mEdif2LrgD28;
    private TextInputEditText mEdif2LrgD29;
    private TextInputLayout mLast;
    private TextInputEditText mEdif2LrgD30;
    private TextInputEditText mEdiTotalFila2;
    private TextInputEditText mEdiPromFila2;
    private TextInputLayout mLasteer;
    private LinearLayout mLycontainer1;
    private TextView mAfftertext;
    private TextInputEditText mEdiObservacioneszszz;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.super_test);
        mTextView54 = findViewById(R.id.textView54);
        mLasdtwwe = findViewById(R.id.lasdtwwe);
        mEdiLargDeds1 = findViewById(R.id.ediLargDeds1);
        mEdiLargDeds2 = findViewById(R.id.ediLargDeds2);
        mTdf = findViewById(R.id.tdf);
        mEdiLargDeds3 = findViewById(R.id.ediLargDeds3);
        mEdiLargDeds4 = findViewById(R.id.ediLargDeds4);
        mEdiLargDeds5 = findViewById(R.id.ediLargDeds5);
        mEdiLargDeds6 = findViewById(R.id.ediLargDeds6);
        mEdiLargDeds7 = findViewById(R.id.ediLargDeds7);
        mEdiLargDeds8 = findViewById(R.id.ediLargDeds8);
        mEdiLargDeds9 = findViewById(R.id.ediLargDeds9);
        mEdiLargDeds10 = findViewById(R.id.ediLargDeds10);
        mEdiLargDeds11 = findViewById(R.id.ediLargDeds11);
        mEdiLargDeds12 = findViewById(R.id.ediLargDeds12);
        mEdiLargDeds13 = findViewById(R.id.ediLargDeds13);
        mEdiLargDeds14 = findViewById(R.id.ediLargDeds14);
        mEdiLargDeds15 = findViewById(R.id.ediLargDeds15);
        mEdiLargDeds16 = findViewById(R.id.ediLargDeds16);
        mEdiLargDeds17 = findViewById(R.id.ediLargDeds17);
        mEdiLargDeds18 = findViewById(R.id.ediLargDeds18);
        mEdiLargDeds19 = findViewById(R.id.ediLargDeds19);
        mEdiLargDeds20 = findViewById(R.id.ediLargDeds20);
        mEdiLargDeds21 = findViewById(R.id.ediLargDeds21);
        mEdiLargDeds22 = findViewById(R.id.ediLargDeds22);
        mEdiLargDeds23 = findViewById(R.id.ediLargDeds23);
        mEdiLargDeds24 = findViewById(R.id.ediLargDeds24);
        mEdiLargDeds25 = findViewById(R.id.ediLargDeds25);
        mEdiLargDeds26 = findViewById(R.id.ediLargDeds26);
        mEdiLargDeds27 = findViewById(R.id.ediLargDeds27);
        mEdiLargDeds28 = findViewById(R.id.ediLargDeds28);
        mEdiLargDeds29 = findViewById(R.id.ediLargDeds29);
        mLast2 = findViewById(R.id.last2);
        mEdiLargDeds30 = findViewById(R.id.ediLargDeds30);
        mEdiTotalFila1 = findViewById(R.id.ediTotalFila1);
        mEdiPromFila1 = findViewById(R.id.ediPromFila1);
        mLast2234 = findViewById(R.id.last2234);
        mLy2mm = findViewById(R.id.ly2mm);
        mEdif2LrgD1 = findViewById(R.id.edif2LrgD1);
        mEdif2LrgD2 = findViewById(R.id.edif2LrgD2);
        mEdif2LrgD3 = findViewById(R.id.edif2LrgD3);
        mEdif2LrgD4 = findViewById(R.id.edif2LrgD4);
        mEdif2LrgD5 = findViewById(R.id.edif2LrgD5);
        mEdif2LrgD6 = findViewById(R.id.edif2LrgD6);
        mEdif2LrgD7 = findViewById(R.id.edif2LrgD7);
        mEdif2LrgD8 = findViewById(R.id.edif2LrgD8);
        mEdif2LrgD9 = findViewById(R.id.edif2LrgD9);
        mEdif2LrgD10 = findViewById(R.id.edif2LrgD10);
        mEdif2LrgD11 = findViewById(R.id.edif2LrgD11);
        mEdif2LrgD12 = findViewById(R.id.edif2LrgD12);
        mEdif2LrgD13 = findViewById(R.id.edif2LrgD13);
        mEdif2LrgD14 = findViewById(R.id.edif2LrgD14);
        mEdif2LrgD15 = findViewById(R.id.edif2LrgD15);
        mEdif2LrgD16 = findViewById(R.id.edif2LrgD16);
        mEdif2LrgD17 = findViewById(R.id.edif2LrgD17);
        mEdif2LrgD18 = findViewById(R.id.edif2LrgD18);
        mEdif2LrgD19 = findViewById(R.id.edif2LrgD19);
        mEdif2LrgD20 = findViewById(R.id.edif2LrgD20);
        mEdif2LrgD21 = findViewById(R.id.edif2LrgD21);
        mEdif2LrgD22 = findViewById(R.id.edif2LrgD22);
        mEdif2LrgD23 = findViewById(R.id.edif2LrgD23);
        mEdif2LrgD24 = findViewById(R.id.edif2LrgD24);
        mEdif2LrgD25 = findViewById(R.id.edif2LrgD25);
        mEdif2LrgD26 = findViewById(R.id.edif2LrgD26);
        mEdif2LrgD27 = findViewById(R.id.edif2LrgD27);
        mEdif2LrgD28 = findViewById(R.id.edif2LrgD28);
        mEdif2LrgD29 = findViewById(R.id.edif2LrgD29);
        mLast = findViewById(R.id.last);
        mEdif2LrgD30 = findViewById(R.id.edif2LrgD30);
        mEdiTotalFila2 = findViewById(R.id.ediTotalFila2);
        mEdiPromFila2 = findViewById(R.id.ediPromFila2);
        mLasteer = findViewById(R.id.lasteer);
        mLycontainer1 = findViewById(R.id.lycontainer1);
        mAfftertext = findViewById(R.id.afftertext);
        mEdiObservacioneszszz = findViewById(R.id.ediObservacioneszszz);
    }
}